apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iam
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: iam
    spec:
      containers:
        - name: app
          image: verseghy/iam
          ports:
            - containerPort: 3001
          imagePullPolicy: Always
          #livenessProbe:
          #  httpGet:
          #    path: /liveness
          #    port: 3001
          #  initialDelaySeconds: 300
          #  failureThreshold: 5
          #readinessProbe:
          #  httpGet:
          #    path: /readiness
          #    port: 3001
          #  initialDelaySeconds: 10
          #  timeoutSeconds: 5
          resources:
            limits:
              memory: 128Mi
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql-password
            - name: DATABASE_URL
              value: mysql://root:$(DB_PASSWORD)@mysql.iam.svc.cluster.local/iam
            - name: REDIS_URL
              value: redis://redis.iam.svc.cluster.local
            - name: SMTP_HOST
              value: ""
            - name: SMTP_USERNAME
              value: ""
            - name: SMTP_PASSWORD
              value: ""
            - name: JWT_RSA_PRIVATE
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: private-key
            - name: JWT_RSA_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: public-key
---
apiVersion: v1
kind: Service
metadata:
  name: iam
  namespace: matverseny-backend
spec:
  selector:
    app: iam
  ports:
    - name: iam
      protocol: TCP
      port: 80
      targetPort: 3001